openapi: 3.0.0
info:
  title: Project microservice
  version: 0.0.1
  description: |
    This is a test.
paths:
  /projects/{projectName}:
    parameters:
      - name: projectName
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Return details about a project
      operationId: GetProject
      responses:
        '200':
          description: list of project names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        'default':
          $ref: '#/components/responses/StatusResponse'
    patch:
      summary: Update project information
      operationId: UpdateProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectUpdate'
      responses:
        'default':
          $ref: '#/components/responses/StatusResponse'
components:
  schemas:
    ProjectUpdate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        requester:
          type: string
        quota:
          enum:
            - x-small
            - small
            - medium
            - large
            - x-large

    Project:
      allOf:
        - $ref: '#/components/schemas/ProjectUpdate'
        - type: object
          properties:
            admins:
              type: array
              items:
                type: string
            users:
              type: array
              items:
                type: string
      required:
        - name
        - description
        - requester
        - quota
        - admins

    Status:
      type: object
      properties:
        status:
          enum: ["ok", "error"]
        message:
          type: string
        project:
          $ref: '#/components/schemas/Project'
      required:
        - status
        - message

  responses:
    StatusResponse:
      description: Return status of an operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status'
